#!/usr/bin/python
# 
#This is a practice of creating new files
#This is the 1st file I am creating
#Version 1
#Auther name: Rose Lee
#
#A little modification
#
#2nd modification of the file
#
#3rd modificaiton
#
